### ISSUE TITLE
1.8.2 installation is broken (No file/folder found for package drf-api-tracking)

### ISSUE THREAD

**Issue by lerela** [lingster/drf-api-tracking#92]
Our pipelines have started failing since 1.8.2 was released (we do not pin bugfix versions). The installation also fails locally. 

Current fix is to pin version 1.8.0.

```
Collecting drf-api-tracking<1.9 (from -r requirements.txt (line 42))
  Downloading drf-api-tracking-1.8.2.tar.gz (15 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'error'
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "/usr/local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/usr/local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-86aoi2pd/overlay/lib/python3.11/site-packages/poetry/core/masonry/api.py", line 41, in prepare_metadata_for_build_wheel
          builder = WheelBuilder(poetry)
                    ^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-86aoi2pd/overlay/lib/python3.11/site-packages/poetry/core/masonry/builders/wheel.py", line 59, in __init__
          super().__init__(poetry, executable=executable)
        File "/tmp/pip-build-env-86aoi2pd/overlay/lib/python3.11/site-packages/poetry/core/masonry/builders/builder.py", line 83, in __init__
          self._module = Module(
                         ^^^^^^^
        File "/tmp/pip-build-env-86aoi2pd/overlay/lib/python3.11/site-packages/poetry/core/masonry/utils/module.py", line 69, in __init__
          raise ModuleOrPackageNotFound(
      poetry.core.masonry.utils.module.ModuleOrPackageNotFound: No file/folder found for package drf-api-tracking
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
```

**Comment by zeus** [comment]
Please publish new version with this fix

**Comment by nickmccullum** [comment]
Thanks for posting this issue, it unblocked me with a recent deployment.
